### PR TITLE
Upgraded dependencies

### PR DESCRIPTION
**Pull request by SKalt**
Since the first publication of this repo a year ago:

- babel-preset-es2015 was deprecated in favor of babel-preset-env
  - babel-* packages are in the process of moving to @babel/* namespaced packages, so more changes are likely in the near future
- the rollup API renamed several variables

This PR adjust for the changing in APIs and upgrade in dependency versions. I avoided making stylistic changes, except in the README, where I updated the "Why Rollup?" section with a quote from Rich Harris's blog on the current differences between Rollup and Webpack.

### CODE REVIEW

**Comment by jakewies** [comment]
Thanks @SKalt for the contribution! If this is a project you actively use I can go ahead and make you a maintainer as well.

**Comment by SKalt** [comment]
Thanks! I'll keep updating it as patches arise in normal use.

**Comment by jakewies** [comment]
Not a problem at all. I haven't used this repo in a quite a while but I am glad someone else is getting use out of it 👍

**Comment by SKalt** [comment]
What do you use as a template these days? I've been using vue-cli's webpack
template for the most part, but this is better suited to lightweight /
framework-free projects.

**Comment by jakewies** [comment]
Really depends on what I'm working on. Most of my personal projects are front end related and I right now I really like using Nextjs and its preconfiguration. I like digging in to custom configurations using all the great tools at our disposal these days, but there are times when I just want to prototype an idea and end up opting for a opinionated configurations like that which comes with Nextjs.

**Comment by SKalt** [comment]
Thanks, I'll take a look at that.

**Pull request merged**
